### ISSUE TITLE
Allow grades for Enrolled_In to be null

### ISSUE THREAD

**Issue by AlexanderKM** [aem1269/gr8#2]
Was messing around trying to enroll in a course and found this. I would push out the changes ( grade = models.FloatField(blank=True, null=True) ) but it looks like the database needs to be sync'd and all that for it to actually work.

**Comment by amccarthy1** [comment]
You should just be able to run
`python manage.py makemigrations`
and then
`python manage.py migrate`

And it should work.

**Comment by AlexanderKM** [comment]
Didn't work :(. Not urgent though, we can talk later

**Comment by MichaelWashburnJr** [comment]
maybe try syncing again after migrating? (Just blindly aiming a gun)

**Comment by AlexanderKM** [comment]
Okay yeah I switched to my desktop, made the changes in the models, saved, ran syncdb, makemigrations, and migrate and then it worked.
