### ISSUE TITLE
Login 'next' causes 404

### ISSUE THREAD

**Issue by MichaelWashburnJr** [aem1269/gr8#3]
### Steps to reproduce:
1. Start the server
2. **Without logging in**, click _All Courses_ under the _Courses_ dropdown menu.
3. Experience the beauty of a 404 error page.

The same error occurs when navigating to other "login required" pages.

Is anyone else experiencing this?

**Comment by MichaelWashburnJr** [comment]
It was my settings. I regret everything.

**Comment by amccarthy1** [comment]
Your testing is bad and you should feel bad.

**Comment by MichaelWashburnJr** [comment]
Apparently I never updated my settings on my laptop to have the correct login url in it.
