### ISSUE TITLE
Course Prerequisites Not Checked

### ISSUE THREAD

**Issue by amccarthy1** [aem1269/gr8#4]
While there is currently no functionality to add a prerequisite to a course, there is also no functionality to check prerequisites when a student is enrolling in a course. Here's a general solution for this problem:
### Backend

Write a method on `Course` that verifies that a user meets the prerequisites for the course
Implement a check in the enrollment code to verify that the prerequisites are met using the above
### Templates

Check that a user meets the prerequisites, and pass that into the `course_info` template.
If a user doesn't meet prerequisites, grey out the 'enroll' button

**Comment by MichaelWashburnJr** [comment]
Are you suggesting we implement the prereq check before prereqs themselves? @aem1269

**Comment by amccarthy1** [comment]
Implemented this feature.
