### ISSUE TITLE
Models need to be updated

### ISSUE THREAD

**Issue by MichaelWashburnJr** [aem1269/gr8#8]
#### The following items need to be added/changed in our database:
- [ ] Keep track of what the grade is out of. I'm not sure if this should be on Course or Course_Code, or some higher entity.  What do you guys think?
- [ ] We need to establish what constitutes a passing grade somewhere, so we can determine if a student has earned their credits.
- [x] We need to move credits to Course_Code.

Edit this or comment if you think of anything else.

**Comment by amccarthy1** [comment]
checking the box
